spring.application.name=Appointment

server.port=9200
spring.datasource.url=jdbc:mysql://localhost:3306/appointmentdb
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


APPOINTMENT_NOT_FOUND=Appointment not found
APPOINTMENT_ALREADY_CANCELLED=Appointment already APPOINTMENT_ALREADY_CANCELLED
